export const rows = [
  {
    id: 1,
    last_name: 'Snow',
    first_name: 'Jon',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 700009,
  },
  {
    id: 2,
    last_name: 'Lannister',
    first_name: 'Cersei',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 300000,
  },
  {
    id: 3,
    last_name: 'Lannister',
    first_name: 'Jaime',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 0,
  },
  {
    id: 4,
    last_name: 'Stark',
    first_name: 'Arya',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 0,
  },
  {
    id: 5,
    last_name: 'Targaryen',
    first_name: 'Daenerys',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 0,
  },
  {
    id: 6,
    last_name: 'Melisandre',
    first_name: null,
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 0,
  },
  {
    id: 7,
    last_name: 'Clifford',
    first_name: 'Ferrara',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 100000,
  },
  {
    id: 8,
    last_name: 'Frances',
    first_name: 'Rossini',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 50000,
  },
  {
    id: 9,
    last_name: 'Roxie',
    first_name: 'Harvey',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 0,
  },
  {
    id: 10,
    last_name: 'Roxie',
    first_name: 'Harvey',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 0,
  },
  {
    id: 11,
    last_name: 'Roxie',
    first_name: 'Harvey',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 0,
  },
  {
    id: 12,
    last_name: 'Roxie',
    first_name: 'Harvey',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 0,
  },
  {
    id: 13,
    last_name: 'Roxie',
    first_name: 'Harvey',
    amount: 9999,
    request_remaning: 9,
    email: '',
    amount_total: 0,
  },
];
